apiVersion: v1
kind: Service
metadata:
  name: hello-http
  namespace: tenx
  labels:
    app: hello-http
spec:
  type: ClusterIP
  selector:
    app: hello-http
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
